version: '3'

services:
  web:
    build: .
    command: /entrypoint.sh --settings=core.settings.${SETTINGS_TYPE}
    volumes:
      - .:/code
    working_dir: /code/core
    ports:
      - "${APP_PORT}:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

volumes:
  postgres_data:
