version: "3"

services:
  web:
    build: .
    entrypoint: ["/entrypoint-${ENTRYPOINT_TYPE}.sh"]
    command: python manage.py runserver --settings=${DJANGO_SETTINGS_MODULE} 0.0.0.0:8000
    volumes:
      - .:/code
    working_dir: /code/core
    ports:
      - "${APP_PORT}:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
      - ENTRYPOINT_TYPE=${ENTRYPOINT_TYPE}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - PIXABAY_API_KEY=${PIXABAY_API_KEY}
      - GOOGLE_OAUTH2_CLIENT_ID=${GOOGLE_OAUTH2_CLIENT_ID}
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - TZ=Europe/Kiev
      - PGTZ=Europe/Kiev
  celery:
    build: .
    entrypoint: ["/entrypoint-${ENTRYPOINT_TYPE}.sh"]
    command: celery -A core.celery worker --loglevel=info
    volumes:
      - .:/code
    working_dir: /code/core
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
    depends_on:
      - db
      - redis
  redis:
    image: "redis:latest"
  flower:
    image: mher/flower:0.9.7
    command: ["flower", "--broker=redis://redis:6379"]
    ports:
      - "5555:5555"
    depends_on:
      - redis

volumes:
  postgres_data:
