# Generated by Django 4.2.4 on 2023-08-19 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='tranlsation',
            new_name='translation',
        ),
    ]
