# Generated by Django 4.2.4 on 2023-08-22 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0002_rename_tranlsation_card_translation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.PositiveSmallIntegerField(choices=[(0, 'New'), (1, 'Learning'), (2, 'Review'), (3, 'Relearning')], default=0)),
                ('due', models.DateTimeField(default=django.utils.timezone.now)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_progress', to='cards.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
