# Generated by Django 4.2.4 on 2023-08-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_cardprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardprogress',
            name='ease',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='cardprogress',
            name='interval',
            field=models.IntegerField(default=10),
        ),
    ]
