# Generated by Django 4.2.4 on 2023-08-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_cardprogress_priority_alter_cardprogress_due_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
