# Generated by Django 4.2.4 on 2023-09-05 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_deck_default_deck_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardAdditionalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cards_additional/')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='cards.card')),
            ],
        ),
    ]
