# Generated by Django 4.2.5 on 2023-09-19 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_learninglog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardprogress',
            name='interval',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cardprogress',
            name='priority',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
