# Generated by Django 4.2.6 on 2023-10-20 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0013_card_image_hash_cardadditionalimage_image_hash_and_more'),
        ('cards', '0013_remove_cardprogress_interval'),
    ]

    operations = [
    ]
