# Generated by Django 4.2.6 on 2023-10-30 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0014_merge_20231020_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='image_hash',
        ),
        migrations.RemoveField(
            model_name='cardadditionalimage',
            name='image_hash',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='image_hash',
        ),
    ]
