# Generated by Django 4.2.6 on 2023-10-30 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0015_remove_card_image_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='hashed_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.hashedimage'),
        ),
        migrations.AddField(
            model_name='cardadditionalimage',
            name='hashed_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.hashedimage'),
        ),
        migrations.AddField(
            model_name='deck',
            name='hashed_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.hashedimage'),
        ),
    ]
