# Generated by Django 4.2.7 on 2023-11-12 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0016_hashedimage_card_hashed_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardprogress',
            name='ease',
            field=models.DecimalField(decimal_places=2, default=1.05, max_digits=5),
        ),
        migrations.CreateModel(
            name='LearnToday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards_total', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learn_today', to='cards.deck')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learn_today', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
