# Generated by Django 4.2.6 on 2023-10-27 12:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_sitecomment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecomment',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
